import "./globals.css";
import localFont from "next/font/local";
import QueryProvider from "@/providers/QueryProvider";
import SessionProvider from "@/providers/SessionProvider";

const satoshi = localFont({
  src: [
    {
      path: "../assets/fonts/Satoshi-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../assets/fonts/Satoshi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/Satoshi-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  fallback: ["sans-serif"],
  display: "swap",
  variable: "--font-sans",
});

export const metadata = {
  title: "Crumbs",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionProvider>
      <QueryProvider>
        <html lang="en" className={satoshi.variable}>
          <body className="bg-surface-green text-white">{children}</body>
        </html>
      </QueryProvider>
    </SessionProvider>
  );
}
